#include "nf_smart18b1.h"
#include <string.h>
static uint32_t step(uint32_t h,uint32_t x){return (h^x)*UINT32_C(16777619);}
static const NfB1Object *find_object(const NfB1World *w,uint32_t id){size_t i;for(i=0;i<w->object_count;i++)if(w->objects[i].id==id)return &w->objects[i];return NULL;}
uint32_t nf_b1_event_digest(const NfB1Event *e){uint32_t h=UINT32_C(2166136261);h=step(h,e->tick);h=step(h,e->actor_id);h=step(h,e->object_id);h=step(h,e->revision_before);h=step(h,e->revision_after);return step(h,(uint32_t)e->action);}
void nf_b1_init(NfB1World *w){if(w)memset(w,0,sizeof(*w));}
bool nf_b1_add(NfB1World *w,NfB1Object obj){if(!w||!obj.id||!obj.material_identity_epoch||w->object_count==NF_B1_MAX_OBJECTS||find_object(w,obj.id))return false;w->objects[w->object_count++]=obj;return true;}
static uint32_t witness(const NfB1World *w,const NfB1Intent *i,const NfB1Object *o){uint32_t h=UINT32_C(2166136261);h=step(h,w->world_revision);h=step(h,i->tick);h=step(h,i->actor_id);h=step(h,i->object_id);h=step(h,(uint32_t)i->action);h=step(h,o->material_identity_epoch);return step(h,o->material_revision);}
NfB1Decision nf_b1_evaluate(const NfB1World *w,const NfB1Intent *i){NfB1Decision d={NF_B1_INVALID,0,0};if(!w||!i||!i->actor_id||!i->object_id||i->action<NF_B1_OPEN||i->action>NF_B1_PUSH)return d;const NfB1Object *o=find_object(w,i->object_id);if(!o)return d;d.material_identity_epoch=o->material_identity_epoch;if(i->tick!=w->tick||i->expected_revision!=w->world_revision||i->observed_material_epoch!=o->material_identity_epoch){d.status=NF_B1_STALE;return d;}if(!o->material_known||!i->actor_observed){d.status=NF_B1_PENDING;return d;}if(!i->physically_reachable||!i->clearance||!o->support_valid||!i->has_contract||(o->locked&&i->actor_id!=o->owner)){d.status=NF_B1_BLOCKED;return d;}if((i->action==NF_B1_OPEN&&o->open)||(i->action==NF_B1_CLOSE&&!o->open)){d.status=NF_B1_DUPLICATE;return d;}d.status=NF_B1_OK;d.witness=witness(w,i,o);return d;}
NfB1Status nf_b1_commit(NfB1World *w,const NfB1Intent *i,NfB1Decision prior){if(!w||!i)return NF_B1_INVALID;NfB1Decision current=nf_b1_evaluate(w,i);if(current.status!=NF_B1_OK)return current.status;if(prior.status!=NF_B1_OK||prior.witness!=current.witness||prior.material_identity_epoch!=current.material_identity_epoch)return NF_B1_STALE;if(w->event_count>=NF_B1_MAX_EVENTS)return NF_B1_FULL;size_t index=0;while(index<w->object_count&&w->objects[index].id!=i->object_id)index++;if(index==w->object_count)return NF_B1_INVALID;NfB1Object next=w->objects[index];if(i->action==NF_B1_OPEN)next.open=1;else if(i->action==NF_B1_CLOSE)next.open=0;next.material_revision++;NfB1Event event={i->tick,i->actor_id,i->object_id,w->world_revision,w->world_revision+1,0,i->action};event.digest=nf_b1_event_digest(&event);w->objects[index]=next;w->events[w->event_count++]=event;w->world_revision++;return NF_B1_OK;}
